# Generated by Django 2.1.1 on 2018-10-10 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181002_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productinbasket',
            name='description',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='image',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='name',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='old_price',
        ),
        migrations.RemoveField(
            model_name='productinbasket',
            name='price',
        ),
        migrations.AddField(
            model_name='productinbasket',
            name='product',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
    ]
